name: baseseq
_target_: strhub.models.baseseq.system.BaseSeq

# Data
patch_size: [ 4, 8 ]  # [ height, width ]

# Architecture
embed_dim: 384
enc_num_heads: 6
enc_mlp_ratio: 4
enc_depth: 12
dec_num_heads: 12
dec_mlp_ratio: 4
dec_depth: 4

# Training
lr: 7e-4
dropout: 0.1

